/** Defense in depth on top of Supabase's exact registered redirect URI check.
 * Never redirect to arbitrary schemes or non-loopback HTTP. When the consent
 * details are available, require an exact base-URI match (query parameters
 * contain the OAuth code/state and are generated by Supabase, not the UI).
 */
export function safeOAuthRedirect(target: string, registered?: string): boolean {
  try {
    const url = new URL(target);
    const allowed =
      url.protocol === 'https:' ||
      (url.protocol === 'http:' && ['localhost', '127.0.0.1', '[::1]'].includes(url.hostname));
    if (!allowed || url.username || url.password || url.hash) return false;
    if (!registered) return true; // Previously approved: Supabase only returns the validated target.
    const base = new URL(registered);
    return (
      base.origin === url.origin &&
      base.pathname === url.pathname &&
      !base.username &&
      !base.password &&
      !base.hash &&
      // A registered query, if present, must not be silently discarded.
      [...base.searchParams].every(([key, value]) => url.searchParams.get(key) === value)
    );
  } catch {
    return false;
  }
}
